ignore:
  - "request.py"

codecov:
  require_ci_to_pass: false
  notify:
    wait_for_ci: false
  
comment:
  layout: "newheader, diff, flags, files, betaprofiling, newfooter"
  show_critical_paths: true
  hide_comment_details: true
